### PR TITLE
Remove numpy even as a testing requirement.

### LINKED ISSUE #158: numpy specified as requirement only for testing.
https://github.com/Blosc/python-blosc/blob/bad3b2e116269499187f3f5c726ad43707f3da03/setup.py#L39

This is not very consistent and breaks builds for users that only require blosc.

### PR DESCRIPTION
**Pull request by esc**
Fixes #158

### CODE REVIEW

**Comment by esc** [comment]
needs to be fixed and updated when 

https://github.com/Blosc/python-blosc/pull/186

is implemented.

**Comment by FrancescAlted** [comment]
Now that #186 is in, I'd say that this is a good time for merging this.

**Comment by FrancescAlted** [comment]
Hmm, I tried merge the changes from master, but CI complains about a missing PY3X symbol.  Strange.

**Comment by FrancescAlted** [comment]
This has stalled for too long, and it is [Closember](https://closember.org), so let's close.

**Pull request closed without merging**
