### PR TITLE
Prepping the 1.2.8 release

### PR DESCRIPTION
**Pull request by esc**

### CODE REVIEW

**Comment by esc** [comment]
Hmmm, appveyor doesn't seem to be running.

**Comment by esc** [comment]
Oh, wait, no, it was just slow to start.

**Comment by esc** [comment]
@FrancescAlted the release notes are a bit long again, but I think this is wise, perhaps.

**Comment by esc** [comment]
Do we want to release anyway and just ignore windows for the time being?

**Comment by FrancescElies** [comment]
:+1:

**Comment by FrancescAlted** [comment]
Hmm, the release notes are pretty short, so I think you rather mean the announcement, and I don't find it that long :)

**Comment by FrancescAlted** [comment]
Regarding the Windows testing, I would say that running it on Windows (not appveyor) once and making sure that it compiles and pass the tests should be enough for now.

**Comment by esc** [comment]
Closing this as 1.2.8 has been released.

**Pull request closed without merging**
