### PR TITLE
[MRG] release buffer

### LINKED ISSUE #102: Memory leak in blosc.decompress in current master
If I run this, I get quickly into memory troubles:

```python
import psutil
x = 'aj lkajfldkfjaoiur 0983 5t93h308 ajlkf n fsfhahtey8 haiuoyajkah ' * 100000
counter = 0
freemem = psutil.avail_phymem() / 1024. ** 3
while freemem > 1:
    cx = blosc.compress(x, typesize=1, clevel=1, shuffle=False, cname='blosclz')
    blosc.decompress(cx)
    freemem = psutil.avail_phymem() / 1024. ** 3
    counter += 1
    if counter % 10000 == 0:
        print('%.2f GB' % freemem)

# 10.56 GB
# 8.66 GB
# 6.75 GB
# 4.84 GB
# 2.91 GB
# 1.01 GB
```
But if I run this, I don't:

```python
import psutil
x = 'aj lkajfldkfjaoiur 0983 5t93h308 ajlkf n fsfhahtey8 haiuoyajkah ' * 100000
cx = blosc.compress(x, typesize=1, clevel=1, shuffle=False, cname='blosclz')
counter = 0
freemem = psutil.avail_phymem() / 1024. ** 3
while freemem > 1:
    blosc.decompress(cx)
    freemem = psutil.avail_phymem() / 1024. ** 3
    counter += 1
    if counter % 10000 == 0:
        print('%.2f GB' % freemem)

# 12.44 GB
# 12.44 GB
# 12.44 GB
# ...
```

That makes me think that decompress is not freeing memory used by the compressed data. And that the bug has been introduced in some recent commit to python-blosc.

I get the leak with python-blosc from master, spiced with c-blosc 1.7.0 (although I think the particular version of c-blosc is not relevant here).  If I run python-blosc 1.2.7 and c-blosc 1.7.0, everything works like a charm - winning combination, because if I use older versions of lz4hc I get segfaults, the reason why I got into all this trouble at first instance.

### PR DESCRIPTION
**Pull request by sdvillal**
This should be ready to merge.  But perhaps we miss a test. I wonder if there is a good way to test for memory leaks.

closes #102

### CODE REVIEW

**Comment by sdvillal** [comment]
As a side note, I would suggest to merge c-blosc 1.7 into master. lz4hc segfaults for me if I use 1.6.2. Instead, I have used 1.7 without any problem. I'm checking roundtrips of many GB of data with different compressor parameterizations, so I think it should be safe enough.

**Comment by esc** [comment]
Can you use the goto: cleanup pattern here to reduce code duplication?

**Comment by esc** [comment]
Also could you check the decompress too, maybe there is a similar issue.

**Comment by sdvillal** [comment]
Yeah, I'm thinking how to do that elegantly. Also need to make travis happy. Will do later.

**Comment by sdvillal** [comment]
Cleanup being this simple, the goto: cleanup formula adds more complexity than it takes.

I have added some meory leak tests, but these might be problematic:
 - Tests are not deterministic anymore; they might fail just because other process allocates memory
 - At the moment, make the build fail for python 3 in travis (killed with 137, bug of mine?). I will need to look at it.
 - Weirdly, for python 2, I get that compress_ptr leaks memory (in my machine) but the test seems to pass happily in travis.

What do you think?

In case you had this branch pulled somewhere, I have rebased to clean git history a bit.

**Comment by sdvillal** [comment]
So I fixed the tests (for py2) and yes, compress_ptr is leaking. I will fix these (compress_ptr leaking, python 3 tests)  during the weekend.

**Comment by sdvillal** [comment]
Ready to go. There were no more leaks beyond the originally reported in decompress (sorry for the false alarms, these were bugs in my tests).

**Comment by FrancescAlted** [comment]
@sdvillal This looks very good to me.  Could you please add an entry in RELEASE_NOTES.rst explaning the fix?  Follow the other entries for the expected format.  Thanks!

**Comment by sdvillal** [comment]
Done

**Comment by FrancescAlted** [comment]
BTW, I like how you implemented the detection of memory leaks.  Not perfect, but functional enough.  Thank again.

**Pull request merged**
