### PR TITLE
add python2 coding headers

### PR DESCRIPTION
**Pull request by danstender**
6b4ee1e and 292aa91 introduced Unicode characters

### CODE REVIEW

**Comment by esc** [comment]
interesting, how did this come to light? Which ones are the unicode chars?

**Comment by danstender** [comment]
On 11/18/18 8:50 PM, Emergency Self-Construct wrote:
> interesting, how did this come to light? Which ones are the unicode chars?

... came up preparing the new Debian package, it broke during the Python 2 build.

SyntaxError: Non-ASCII character '\xc3' in file blosc/toplevel.py on line 744, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

SyntaxError: Non-ASCII character '\xc3' in file blosc/test.py on line 259, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Best,
DS

**Comment by esc** [comment]
O.K. do you need a new release, or can you patch it at the Debian level?

**Comment by danstender** [comment]
On 11/18/18 8:57 PM, Emergency Self-Construct wrote:
> O.K. do you need a new release, or can you patch it at the Debian level?
I've patched it here, that'll do until the next release.

Thx for feedback and quick merge,
DS

**Pull request merged**
