### PR TITLE
Appveyor v2 - fixes

### PR DESCRIPTION
**Pull request by FrancescElies**
So far this PR provides:
- Renaming of the file-name extension from .yaml to .yml
- Badge

I can't see if Webhook settings are still missing or they are already there.
I guess the link for the badge will need afterwards to be corrected.

For my fork I am getting the following error
```
c-blosc/blosc\shuffle-sse2.c(14) : fatal error C1189: #error :  SSE2 is not supported by the target architecture/platform and/or this compiler. 
```

This is not ready yet.

### CODE REVIEW

**Comment by esc** [comment]
Not being able to compile and making Appveyor work are orthogonal concerns, would like to merge this now.

**Comment by esc** [comment]
and thx btw. much appreciated.

**Comment by FrancescElies** [comment]
I could separate them in two PRs badge and config file fixes or you could merge it and later on see what's going wrong, as you wish.

For the moment I see the following:
screen shot 2015-06-11 at 22 34 03

You could check the badge at https://github.com/FrancescElies/python-blosc/tree/appveyor, it says build passing, mmm not sure if that is correct, maybe I miss-configured something.

**Comment by FrancescElies** [comment]
If I click on the appveyor "green" badge I see 
```
Build started
git clone -q --branch=master git://github.com/Blosc/python-blosc.git C:\projects\python-blosc
git checkout -qf 0b1939278284bb9e594fab1a76bf31c65ab876a1
Specify a project or solution file. The directory does not contain a project or solution file.
```

**Comment by esc** [comment]
Yeah, I think the badge is for master, anyway, let's get this merged in now.

**Comment by esc** [comment]
Also, can you switch the badge to point to the 'esc' repo instead of FrancescAlted.

**Comment by FrancescAlted** [comment]
Ok, so the problem was that I was using a '.yaml' file instead of '.yml' right?  Good catch!

**Comment by FrancescElies** [comment]
yes, that was it

**Comment by FrancescElies** [comment]
I believe Appveyor fails because `__SSE2__` is not defined and `M_IX86_FP = 0`, could be this the problem?
https://github.com/Blosc/python-blosc/blob/master/c-blosc/blosc/shuffle-common.h#L30-L33

If one prints them, you would get the following output:
```
__SSE2__ = __SSE2__ 
_MSC_VER = 1500
_M_X64 = _M_X64 
_M_IX86 = 600 
_M_IX86_FP = 0
```

**Comment by FrancescAlted** [comment]
But looking at the output, it seems to me that `__SSE2__` *is* defined with a value of '__SSE2__' right?  Also, by the output, it seems that the appveyor host is Win64 (which should run on hardware that implements SSE2), so this is pretty strange.

**Comment by FrancescElies** [comment]
I used this to get those prints:
```
#define STRING2(x) #x
#define STRING(x) STRING2(x)

#pragma message("__SSE2__ = " STRING(__SSE2__))
#pragma message("_MSC_VER = " STRING(_MSC_VER))
#pragma message("_M_X64 = " STRING(_M_X64))
#pragma message("_M_IX86 = " STRING(_M_IX86))
#pragma message("_M_IX86_FP = " STRING(_M_IX86_FP))
```
--------
Appveyor 32 bits
```  Environment: PYTHON=C:\Python27, PYTHON_VERSION=2.7.8, PYTHON_ARCH=32  ```
In the case of a constant not being defined I think it prints out the name inside STRING(), but I'm not completely sure, sorry for the confusion, does anybody know a better way of checking the value of those constants?
In that case we would have two constants not defined __SSE2__ and  _M_X64

--------
Appveyor 64 bits
``` Environment: PYTHON=C:\Python27-x64, PYTHON_VERSION=2.7.8, PYTHON_ARCH=64 ```
```
__SSE2__ = __SSE2__ 
_MSC_VER = 1500
_M_X64 = 100 
_M_IX86 = _M_IX86 
_M_IX86_FP = _M_IX86_FP
```
Error
```
c-blosc/blosc\shuffle.c(13) : fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory 
```

**Comment by esc** [comment]
I see the 'stdbool.h' error on my Amazon Windows test instance.

**Comment by FrancescAlted** [comment]
Looks like this is not supported on Visual Studio compilers < 2013.  Trying a fix in b416370.

**Pull request merged**
