### PR TITLE
use vendored distutils.version to avoid DeprecationWarnings

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
importing blosc on Python3.10 shows the following error:

```
python -W error
Python 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:38:57) [GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import blosc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/graingert/miniconda3/envs/dask-distributed-310/lib/python3.10/site-packages/blosc/__init__.py", line 37, in <module>
    from blosc.toplevel import (
  File "/home/graingert/miniconda3/envs/dask-distributed-310/lib/python3.10/site-packages/blosc/toplevel.py", line 11, in <module>
    from distutils.version import LooseVersion
  File "/home/graingert/miniconda3/envs/dask-distributed-310/lib/python3.10/distutils/__init__.py", line 19, in <module>
    warnings.warn(_DEPRECATION_MESSAGE,
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
>>> 
```

**Comment by graingert** [comment]
using `packaging.version` is probably preferred longterm but I think on balance `distutils.version.LooseVersion` isn't much code to vendor and saves a 3rd party dep

**Review by FrancescAlted — APPROVED** [review]
LGTM

**Comment by DimitriPapadopoulos** [comment]
[PEP 632](https://peps.python.org/pep-0632/#migration-advice) advises `distutils.version` is replaced by the `packaging` package.

**Pull request merged**
