### PR TITLE
adding c-blosc v1.16.0

### PR DESCRIPTION
**Pull request by esc**
do the usual release dance! :dancer: :man_dancing:

### CODE REVIEW

**Comment by esc** [comment]
@FrancescAlted @albertosm27  @scopatz - the continuous integration seems to suggest that their is a regression in c-blosc and the empty string seems once again to be incompressible. The error is the same across all versions on python:

```
$ nosetests --with-doctest blosc
..F...............................
======================================================================
FAIL: Doctest: blosc.toplevel.decompress
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python/3.7.1/lib/python3.7/doctest.py", line 2198, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for blosc.toplevel.decompress
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/blosc/toplevel.py", line 519, in decompress
----------------------------------------------------------------------
File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/blosc/toplevel.py", line 554, in blosc.toplevel.decompress
Failed example:
    b"" == blosc.decompress(blosc.compress(b"", 1))
Exception raised:
    Traceback (most recent call last):
      File "/opt/python/3.7.1/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest blosc.toplevel.decompress[6]>", line 1, in <module>
        b"" == blosc.decompress(blosc.compress(b"", 1))
      File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/blosc/toplevel.py", line 564, in decompress
        return _ext.decompress(bytesobj, as_bytearray)
    blosc_extension.error: Error -1 while decompressing data
```

**Comment by esc** [comment]
here is the previous issue on this, for reference: https://github.com/Blosc/c-blosc/issues/242

**Comment by FrancescAlted** [comment]
That's unfortunate . I'll try to have a look into this tomorrow .

**Comment by esc** [comment]
Yes, maybe it would make sense to run all python-blosc and bloscpack unit tests as part of the c-blosc release schedule? Alternatively, we could think about setting up a CI job that always tests the latest c-blosc master against the latest release of python-blosc and bloscpack.

**Comment by FrancescAlted** [comment]
This should be fixed in https://github.com/Blosc/c-blosc/commit/4f327d58c7c2581221385900fa6ff94af12f54e0.  Expect a new C-Blosc release very soon.

**Comment by esc** [comment]
@FrancescAlted works, thanks! #181 merges the new version.

**Pull request closed without merging**
