### PR TITLE
Release v1.2.5

### PR DESCRIPTION
**Pull request by esc**
Most things are in place, just some more manual work that needs to be done.
Getting the ball rolling with this pull request.

### CODE REVIEW

**Comment by esc** [comment]
@FrancescAlted I presume it is OK for you if I go ahead and release it?

**Comment by esc** [comment]
Not sure exactly what stopped me here, I presume that it was issues with bloscpack/bcolz segfaulting and fear of including ``v1.5.2``.

**Comment by esc** [comment]
Or should we keep the GIL here too?

**Comment by FrancescAlted** [comment]
Yes, before releasing, I would hold the GIL here as well.  With that, I would include blosc 1.5.2 (or 1.5.3, which I should be releasing really soon now).  In case crashes appear, maybe they will offer another view on what's the problem with 1.5 series.

**Comment by esc** [comment]
rebased and updated missing docs for ``set_blocksize`` and blosc v1.5.3

**Comment by esc** [comment]
Rebased again, now just missing docs for ``set_blocksize``.

**Comment by esc** [comment]
Ok, #76 was never commented on, so suggest to leave it and release.

**Comment by esc** [comment]
Release notes now also contain the correct blosc version.

**Comment by esc** [comment]
tests pass on an aws windows instance

**Comment by esc** [comment]
All Travis tests on Linux with Python 2.6 2.7 3.2 3.3 and 3.4  pass!

**Comment by esc** [comment]
I updated the ``ANNOUNCE.rst``, @FrancescAlted woud you care for a review?

**Pull request merged**
