### PR TITLE
remove instructions about using the subtree-merge script

### PR DESCRIPTION
**Pull request by esc**
since the script is gone now.

### CODE REVIEW

**Comment by esc** [comment]
@FrancescAlted can you merge?

**Comment by FrancescAlted** [comment]
The script is gone, but I thought the idea was to use the https://github.com/Blosc/subtree-merge-blosc repo.  So what I would do is just to update the docs.

**Comment by esc** [comment]
You can only use the script if it has been comited into the repository.

**Comment by esc** [comment]
I'll get this merged up, we can always decide to bring it back in future.

**Pull request merged**
